### ISSUE TITLE
Help with Extension writing.

### ISSUE THREAD

**Issue by sggreener** [PhilippSalvisberg/sqldev#1]
Philipp,

I can't find a direct email address for you so I apologise in advance for using the issues subsystem to ask the following.

The page you wrote:

https://github.com/PhilippSalvisberg/sqldev

Seems to be a good description of the steps required to write an extension. 

I am working with a group of programmers trying to write our own extension (actually porting an old one) but we are struggling with knowing the steps to actual build one.  We can't find reliable and informative descriptions of the processes (and resources) needed to implement an extension.

Our extension has some XML based dialogs but is mainly Java based eg Right mouse click on table node, select action, execute Java.

Does your descriptive cover all that is needed? Are there any other resources (such as https://jcp.org/en/jsr/detail?id=198) that you would recommend we read? Would you mind if we asked other questions as we go along?

regards
Simon Greener
Oracle, Oracle Spatial, PL/SQL expert and user of utPLSQL

**Comment by PhilippSalvisberg** [comment]
This repository contains mainly the tutorials of a workshop I did for a customer to enable them building their own SQL Developer extensions.

However, this repository contains also some additional [documentation](https://github.com/PhilippSalvisberg/sqldev/blob/8d9116cdf606708711f4d9d583d4276324cc6924/README.md#documentation). I recommend to have a look at the [Trigger Hooks](https://github.com/PhilippSalvisberg/sqldev/blob/8d9116cdf606708711f4d9d583d4276324cc6924/docs/trigger-hooks.md) and the [External Links](https://github.com/PhilippSalvisberg/sqldev/blob/8d9116cdf606708711f4d9d583d4276324cc6924/README.md#external-links).

Based on these information you should be able to build your own SQL Developer extensions.

Furthermore, if you have specific questions I encourage you to ask them in the [SQL Developer forum](https://community.oracle.com/community/groundbreakers/database/developer-tools/sql_developer/content?query=extension). @thatjeffsmith, @krisrice, @bjeffrie and other SQL Developer team members as well as the whole Oracle community are usually very eager to help.

Good luck!

**Comment by krisrice** [comment]
@sggreener  XML based dialogs, haven't changed are to hitting some issue ?

**Comment by sggreener** [comment]
Sorry for the delay.

Thank you for this valuable information. 

My team will be having another attempt to create a basic extension starting next week.

Regards
Simon

**Comment by sggreener** [comment]
> @sggreener XML based dialogs, haven't changed are to hitting some issue ?

It is not the XML based dialogs that are the problem. It is implementing calls to substantial amounts of java.

**Comment by PhilippSalvisberg** [comment]
> Thank you for this valuable information.

You're welcome.

> My team will be having another attempt to create a basic extension starting next week.

Great. I suggest to the work through the workshops starting with the environment setup as described in the [README](https://github.com/PhilippSalvisberg/sqldev/blob/master/README.md).

Please let me know if you were successful. You can connect me also via [my blog](https://www.salvis.com/blog/contact/), [Twitter](https://twitter.com/phsalvisberg) or [LinkedIn](https://www.linkedin.com/in/philippsalvisberg/).

**Comment by PhilippSalvisberg** [comment]
I had an exchange via email with a student from University of Tasmania. His team works on migrating the [GeoRaptor](https://sourceforge.net/projects/georaptor/) extension from ESDK 1 (SQL Developer < 4) to ESDK 2 (SQL Developer >= 4). I think I could help them solving the blocking issues. Hence I'm closing this issue.

**Comment by sggreener** [comment]
Phillip,

Yes, these students are working on bringing an old (0.9-3.2) extension up to date after it broke over 5+ years ago.

Thank you for all your help.

Regards
Simon

⁣39 Cliff View Drive, Allens Rivulet, Tas 7150
(H) 0362396397
(M) 0418396391
www.spatialdbadvisor.com / www.spdba.com.au
