### ISSUE TITLE
Sort order and custom query

### ISSUE THREAD

**Issue by yerba1704** [PhilippSalvisberg/sqldev#5]
Hi Philipp!

For [the ora* CODECOP project](https://github.com/yerba1704/occ) (a framework to help you define rules for your database users and verify these rules with SQL statements) I created a XML navigator extension for SQL Developer (https://github.com/yerba1704/occ-sqldeveloper). When you look at https://github.com/yerba1704/occ-sqldeveloper/blob/main/occ_navigator_extension.xml you can see that for the 5 severities I specified the weight attribute to have a correct sort order. But unfortunately it doesnt' work:
![image](https://github.com/PhilippSalvisberg/sqldev/assets/135860924/75720e67-0107-405d-ae4e-20299745d907)
Do you have any idea how to solve this problem???

Question 2 is about user dependent queries in the editor:
The editor extension (https://github.com/yerba1704/occ-sqldeveloper/blob/main/occ_editor_extension.xml) define one query (displays > display > query > sql). Do you know how to define two queries dependent on the connected user? 
Practical usecase is that the normal user display all columns except the owner column, but the "superuser" should display this extra owner column (of course with polymorphic table functions this should be solved, but it would be much easier if there is a "xml definition way").
Any ideas???

Thanks for your help! :)

**Comment by PhilippSalvisberg** [comment]
Question 1: IMO the weight attribute is considered only for folders and ignored for leaf nodes. Leaf nodes seem to be sorted by the UI according to the name. Hence you have to choose a name that reflects your expected order. Something like this:

- `1-Blocker`
- `2-Critical`
- `3-Major`
- `4-Minor`
- `5-Info`

Question 2: Why not provide a null column value (or `***` or ...) for non-superusers? I currently do not see another way to handle it within the XML definition. And as you said you could handle it with a table function or an SQL macro which provides a different number of columns based on the user.

**Comment by yerba1704** [comment]
Thanks a lot for your reply. I will think about the pros and cons and then decide...
